// Next Utils
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

export default function Home () {
  const [redTouched, setRedTouched] = useState(false)
  const [blueTouched, setBlueTouched] = useState(false)

  return (
    <div>
      <Head>
        <title>FELIZ CUMPLEAÑOS ~ NICOLÁS UGAL LUQUE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='relative w-full h-screen bg-red-500 overflow-hidden'>
        <div className='absolute top-0 bottom-0 left-0 right-0 z-10 bg-white h-max px-4 py-10 m-auto text-center'>
          <h1 className='text-3xl font-black'>Selecciona color</h1>
        </div>
        <div onClick={() => setRedTouched(true)} className='bg-red-500 h-1/2 skew-y-12 flex items-center justify-center'>
          {redTouched && (
            <div className='w-1/2 h-1/2 -skew-y-12 mb-14 shadow-md bg-white'>
              <Image
                src='/mcbook.webp'
                layout='fill'
                objectFit='contain'
                alt='mcboook'
              />
            </div>
          )}
        </div>
        <div onClick={() => setBlueTouched(true)} className='bg-blue-500 h-[100%] skew-y-12 flex justify-center items-center'>
            {blueTouched && (
              <div className='w-60 h-60 -skew-y-12 -mt-80 shadow-md bg-white'>
                <Image
                  src='/patinete.webp'
                  layout='fill'
                  objectFit='contain'
                  alt='mcboook'
                />
              </div>
            )}
        </div>
      </div>

    </div>
  )
}
